apiVersion: v1
kind: ReplicationController
metadata: 
  name: monitoring-heapster-v4
  namespace: default
  labels: 
    k8s-app: heapster
    version: v4
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    k8s-app: heapster
    version: v4
  template: 
    metadata: 
      labels: 
        k8s-app: heapster
        version: v4
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: gcr.io/google_containers/heapster:v0.14.3
          name: heapster
          resources:
            limits:
              cpu: 200m
              memory: 2.5Gi
          command:
            - /heapster
            - --source=kubernetes:''
          volumeMounts: 
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: monitoring-token
              mountPath: /etc/kubernetes/kubeconfig
              readOnly: true

      volumes: 
        - name: ssl-certs
          hostPath: 
            path: /etc/ssl/certs
        - name: monitoring-token
          secret:
            secretName: token-system-monitoring

